### ISSUE TITLE
Make a new mentor card 

### ISSUE THREAD

**Issue by aa-deet-eeya** [glugmvit/gwoc#18]
There's a noticeable difference between the font sizes of Mentor and Participant Cards, and since the current website layout has them side by side, I suggest we should have them similar font size.
The image files can be found in `/public/images/`by the name CARD1 and CARD2

<img src="https://user-images.githubusercontent.com/26107248/97109927-2f88db80-16fc-11eb-90fe-34a754a79428.png" width="47%"/> <img src="https://user-images.githubusercontent.com/26107248/97109950-47f8f600-16fc-11eb-88a2-fb0c88ce7a9b.png" width="46.25%"/>

**Comment by prakruthi3** [comment]
![1](https://user-images.githubusercontent.com/44273409/97142977-c8186d80-1787-11eb-8e97-628c4cc041ba.png)
![2](https://user-images.githubusercontent.com/44273409/97142983-ca7ac780-1787-11eb-9576-7808f4a06ba0.png)

Card changed
